name: loading_empty_error
description: Conjunto de widgets úteis em vários apps da ESIG.
version: 3.0.1
homepage: https://github.com/mobile-esig/loading-empty-error

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
